name: Publish

on:
  push:
    branches:
      - master

jobs:
  docker-publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current branch name
        id: branch_name
        run: echo ::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})

      - name: Get repository name
        id: repo_name
        run: echo ::set-output name=REPO_NAME::$(echo "${GITHUB_REPOSITORY#*/}" | awk '{print tolower($0)}')

      - name: Set image tag
        id: set_image_tag
        run: echo ::set-output name=IMAGE_TAG::${{ secrets.DOCKER_USERNAME }}/${{ steps.repo_name.outputs.REPO_NAME }}:${{ steps.branch_name.outputs.BRANCH_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ steps.set_image_tag.outputs.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ steps.set_image_tag.outputs.IMAGE_TAG }}

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
